name: dbutils
description: Database utilities class library for SQLite and any number of other DBMS implemented in the future.

version: 2.1.1

homepage: https://github.com/AndriousSolutions/dbutils
repository: https://github.com/AndriousSolutions/dbutils

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# Web only.
  # https://pub.dev/packages/firebase_core
  firebase_core: ^0.4.0

  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^0.16.0

  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.13.0

  # RealTime Database
  # https://pub.dev/packages/firebase_database
  firebase_database: ^3.0.0

  # https://pub.dartlang.org/packages/sqflite#-changelog-tab-
  sqflite: ^1.0.0

  # https://pub.dartlang.org/packages/path_provider#-changelog-tab-
  path_provider: ^1.0.0

  # https://pub.dev/packages/path
  path: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

