name: dbutils
description: Database utilities class library for SQLite and any number of other DBMS implemented in the future.
version: 1.0.0
author: Greg Perry <support@andrioussolutions.com>
homepage: https://github.com/AndriousSolutions/dbutils
repository: https://github.com/AndriousSolutions/dbutils

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dartlang.org/packages/sqflite#-changelog-tab-
  sqflite: ^1.0.0

  # https://pub.dartlang.org/packages/path_provider#-changelog-tab-
  path_provider: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

